FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip setuptools wheel
RUN pip install --no-cache-dir --prefer-binary -r requirements.txt

# Copy model files and application code
COPY chest_xray_classification_model.h5 .
COPY tb_risk_model.pkl .
COPY scaler.pkl .
COPY main.py .

EXPOSE 5000

CMD ["python", "main.py"]